### ISSUE TITLE
Will a super nice camera allow us to just take one picture?

### ISSUE THREAD

**Issue by DeirdreLoughnan** [temporalecologylab/TreeRings#1]
@FrederikBaumgarten thanks for looking into what kind of camera and lens we might be able to use to take one mega picture and capture the level of detail we would need.

Since this is a major deciding factor in how the project proceeds, we should try to figure this out in the next week or two. 

@FrederikBaumgarten have you looked into renting the camera further? Is there a day you would want to go to the store and try to rent the camera? 

In looking over the [Beau photo website](https://www.beauphoto.com/rentals/rental-cameras/#1463677858622-091d821d-0ada) I noticed that they require a deposit equal the cost of the camera, which might be challenging.

**Comment by FrederikBaumgarten** [comment]
@DeirdreLoughnan Once you have a sanded core ready (and eventually also a cookie) I will ask the store if I can come by to make this test foto. So let me know when you have it! Looking forward to this!

**Comment by lizzieinvancouver** [comment]
> Looking forward to this!

Me too!

**Comment by DeirdreLoughnan** [comment]
@FrederikBaumgarten We now have sanded the cookies!

I know they are not perfect and have some striations, but they were sanded using the different grades and should work for now!

**Comment by DeirdreLoughnan** [comment]
@FrederikBaumgarten you mentioned that you no longer think this will be our solution. For documentation sake, could share some notes or a few points about what made you reach this conclusion?

**Comment by FrederikBaumgarten** [comment]
> @FrederikBaumgarten you mentioned that you no longer think this will be our solution. For documentation sake, could share some notes or a few points about what made you reach this conclusion?

sure: Depending on the ring width and cellular properties (e.g. ring- vs. diffuse porous) as well as the exact analysis of interest (e.g. simply ring width or more sophisticated parameters such as cell wall thickness etc.) a one shot photo with a 400MP resolution might be indeed a possible solution for samples not exceeding 50cm in range. However this comes at a price (at least 12'000 CAD) for which several skippys can be build. Hence while the idea is most likely feasable for basic tree ring analysis it might be only reasonable to do it once pricing of this recent technology has come down in a couple of years.

**Comment by lizzieinvancouver** [comment]
@FrederikBaumgarten Thanks for your work on this! Seems like cool technology not quite ready for our application yet.
