### ISSUE TITLE
Finding a table

### ISSUE THREAD

**Issue by DeirdreLoughnan** [temporalecologylab/TreeRings#10]
@soleil-nocturne123 , you texted me Saturday with [this option from Uline](https://www.uline.ca/Product/Detail/H-9626-WOOD/Heavy-Duty-Packing-Tables/Mobile-Heavy-Duty-Packing-Table-72-x-48-Composite-Wood-Top) for a table. Could you provide some justification for why you think this table is what we need, given that it is $1,152?

My questions are as follows:
- Could you confirm what the dimensions of the frame are? Is it 80 x 80 cm?
- Did you measure the space by the white board? Would a table that is 1.8m actually fit in that space? 
- Do we need such a long table? If so why?
- I think a table without wheels is preferred for stability, do you or @afong3 feel differently?

I feel like there are better, less expensive options at Uline, such as [this 48 x 36"](https://www.uline.ca/BL_3853/Industrial-Packing-Tables?keywords=tables) one for $455. Is there a reason why this option would not work?

@soleil-nocturne123 could you please address the above questions here in the git issue and review some of the other options available at Uline by Wednesday March 6?

**Comment by lizzieinvancouver** [comment]
@soleil-nocturne123 and @DeirdreLoughnan Thanks for your help on getting this sorted! I am personally okay with one with wheels if they lock really well. We can also discuss this in open scrum if someone can bring the dimensions of the capture device *and* the space we have available.

**Comment by afong3** [comment]
@DeirdreLoughnan @soleil-nocturne123 @lizzieinvancouver The frame dimensions of the device are 1m x 1m but would benefit from one dimension having some extra space for the electronics and potentially a laptop. Wheels could work but I think stationary would be ideal - the machine isn't super heavy but there is a lot of vibration with the acceleration / deceleration of the camera mounting area. The floor seems rather slick so the point contact of the wheels might slide ever so slightly when locked.

**Comment by lizzieinvancouver** [comment]
@afong3 Thanks! You and @DeirdreLoughnan have convinced me against wheels, but I like having some extra space -- I do think we'll need some room beyond the frame for computing etc..

**Comment by afong3** [comment]
Just checked on the space in the lab - if we want to put the machine where the whiteboard is now we can as the whiteboard fits by the door. There might be some funky cart-turning situations to access the far side of the lab but should be more manageable than in the doorway. Also the 48" x 36" will be 4" too short in one dimension.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @afong3 Thanks for thinking on this more this afternoon! I did some quick googles and found one option to explore [Mcmaster Carr](https://www.mcmaster.com/products/build-your-own-workbenches/) they also have [office tables](https://www.mcmaster.com/products/office-tables/). I have not checked Uline or elsewhere (must get back to some late teaching tasks).

**Comment by soleil-nocturne123** [comment]
The reason why I want a table with wheels is because it would be more convenient if we want to move the system to other spot in the future. But as Adam said, if it potential creates some potential vibration issues, maybe we should go with a stationary one.

I am quite against placing it by the doorway though. I think the best spot for now would be in front of the whiteboard. I think ideally a square 48" x 48" would be good -- We can place the computing devices on the bench beside the whiteboard. However, I couldn't find one from Uline or McMaster Carr. The smallest dimension that fits for now is 72" x 48".

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver it looks like Master Carr custom tables only go up to 36" wide, which is about 10 cm shy of the minimum we would want. I will look into companies that make custom tables for manufacturing. I think that could be a good route!

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan There's a nice looking table in the lab just now ... see what you and @afong3 think and -- if good -- let's close this!

**Comment by DeirdreLoughnan** [comment]
It fits perfectly and looks great! Thanks @afong3 for putting it together.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I forgot to ask what you came up with in the end! Can you update here with how you made it work so we have a record? Then close again.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver in the end I purchased an [industrial packing table from ULine](https://www.uline.ca/BL_3853/Industrial-Packing-Tables), I bought the 60 X 36" one with a composite wood top. 

To make it portable, I also bought a piece of MDF board that the frame can be mounted to. I think mounting the frame will also keep it from vibrating. But we probably want to buy or 3D print new mounts, since the frame's current ones are not built with the most robust material.
