### ISSUE TITLE
Image Focusing

### ISSUE THREAD

**Issue by afong3** [temporalecologylab/TreeRings#11]
To get a successful image stitch, it is necessary to have in focus images with sufficient overlap. While it would be great to have auto focus, it greatly limits the camera options. 

Some ideas so far:
- Get a camera + lens which can auto-focus
- Figure out a 'focus stack' of images in the same location and choose the most in focus image. 
- Leveling the cookies in both x and y direction before taking images

**Comment by lizzieinvancouver** [comment]
Some of the comments in the [labgit issue #14 ](https://github.com/temporalecologylab/labgit/issues/14) are relevant here: 

> 
> From questions about lab camera during Scrum 19 March 2024:
> 
> For reference the current DSLR in the lab is Canon EOS 30D and the best magnification the lenses we have can offer is 1:1. CaptuRING researchers used a Tokina 100mm f/2.8 AT-X PRO 1:1 Macro (I think, I had to look super closely at their images) lens for their construction.
> 
> The technique for taking photos at multiple depths and then stitching them at the parts of highest definition is called focus stacking and is a very common technique for macro wildlife photographers, and there are also plenty of tutorials online for doing this manually (although given we're in this lab, it makes the most sense to try and automate that somehow?). Focus stacking can be done in Photoshop which we should all have easy access to.
>

**Comment by lizzieinvancouver** [comment]
@afong3 @ngoj1 One more thing to think about! I chatted with a tree ring colleague Friday and they use both an autoflash and additional light sources for the best images. Not sure what our plan is but something to think about.

**Comment by lizzieinvancouver** [comment]
@afong3 Sounds good.
