### ISSUE TITLE
Laptop with Ubuntu Distribution + Admin Privileges

### ISSUE THREAD

**Issue by afong3** [temporalecologylab/TreeRings#12]
To setup the Jetson Orin Nano (the single board computer which will be managing the image stitching), we need a computer with Ubuntu with an x86 CPU architecture and 80GB of free storage. While we can flash a MicroSD card to have the OS for the Jetson, we are trying to flash the OS onto an SSD onboard the Jetson. The only method to do this is by [connecting a Ubuntu 18.04 or 20.04 host device to the Jetson via USB-C](https://youtu.be/q4fGac-nrTI?t=100). 

One option is to just convert a laptop we currently have to run Ubuntu, but there are none available for this. A x86 CPU is in almost every Windows laptop so it should be relatively easy to acquire. I'll try to find a few cheap options. 

Some options:

[Dell Inspiron 15](https://www.dell.com/en-ca/shop/cty/pdp/spd/inspiron-15-3520-laptop/ni153520_s251001es?tfcid=54598298&&gacd=9683519-3042-5761040-266312346-0&dgc=ST&SA360CID=71700000110509327&gad_source=1&gclid=CjwKCAjwh4-wBhB3EiwAeJsppFxRd75v6fIDgLeKhNRJIELvDYR4IZFH6F1mY98IWLmMsLYP_hdK6xoCCOgQAvD_BwE&gclsrc=aw.ds) - $350
[Lenovo 500w Gen 3](https://www.lenovo.com/ca/en/p/laptops/lenovo/windows-edu-laptops/500w-g3/82j3a000us?cid=ca:sem|se|google|pmax_consumer_mainstream||||18331993674|||shopping|mix|consumer&gad_source=1&gclid=CjwKCAjwh4-wBhB3EiwAeJsppOsfqH_5x8utyJ_UfH7tB2v1B1eprICywMrUHK7qCmlhtwltyq9cshoCwMUQAvD_BwE) - $200
[Refurbished HP](https://www.bestbuy.ca/en-ca/product/refurbished-good-hp-probook-x360-11-g3-ee-1-10ghz-intel-celeron-n4000-4gb-ram-128gb-ssd-dual-webcam-usb-c-touchscreen-windows-11-pro/17234491) - $150
[Lenovo IdeaPad 1](https://www.lenovo.com/ca/en/p/laptops/ideapad/ideapad-100/ideapad-1-gen-7-(15-inch-amd)/82vg0041us?cid=ca:sem|se|google|shopping_pcamd|gs_servers||82VG0041US|1756627594|71352363480|pla-1272503098740|shopping|brand&gad_source=1&gclid=CjwKCAjwh4-wBhB3EiwAeJsppJexsOf1ti1EQiJFUa5NPlJm5O4kvGv-0argIiPinOFB0DMrx4ZgfBoCwwMQAvD_BwE) - $350

**Comment by lizzieinvancouver** [comment]
Got it... I emailed Microserve.

**Comment by lizzieinvancouver** [comment]
@afong3 Okay, so the company UBC offered is a DISASTER to work with ... it would take ages to get a quote and then they expect 'a custom build' ... so we will not get the CFI discount for computing as our time and reasonable prices are WAY more important. Pick the best laptop for the job, buy it on the corporate card and bill to PAKF -- please aim to be keep total cost for laptop below 600 CAD incl ship and tax (let me know if not possible).
