### ISSUE TITLE
Sample Leveling

### ISSUE THREAD

**Issue by afong3** [temporalecologylab/TreeRings#14]
One of the requirements from the cookie samples is to have the sanded surface of the cookie be parallel to the table its resting on. During the sanding process, it would be very cumbersome to need to keep both sides of the cookie perfectly parallel. To combat this, a leveling table was designed to easily adjust for small angle differences between the top and bottom plane of the cookie.

![cookie_leveled](https://github.com/temporalecologylab/TreeRings/assets/62484502/e2b94c5c-f419-46d0-a1ee-5b39f79d512d)
![cookie_leveled2](https://github.com/temporalecologylab/TreeRings/assets/62484502/62d9530f-4fdd-49d8-9de2-ac269f4fdd49)

**Comment by lizzieinvancouver** [comment]
@afong3 Looks super cool!
