### ISSUE TITLE
Buying an OpenBuilds BlackBox Controller

### ISSUE THREAD

**Issue by afong3** [temporalecologylab/TreeRings#19]
I've tidied up the machine - all the wires are now enclosed in corrugated tubing. It's looking much prettier now! 

![image](https://github.com/temporalecologylab/TreeRings/assets/62484502/6989938f-826d-4a22-bd0b-4f4b37e641ab)

But now I'm trying to tackle the rats nest of the current Arduino control board. To connect to the motors, very flimsy Dupont connectors were soldered on the wires. While everything is still functional, the connections are not locking and are prone to being pulled out when the Arduino is jostled. 

![image](https://github.com/temporalecologylab/TreeRings/assets/62484502/1d0ba602-ea3f-4cc3-ab2f-fbde2540b39d)

One solution to this is to design a PCB, have it printed, and probably have to do a couple of iterations. Another option would be to create a make shift protoboard converter from Dupont connectors to screw terminals. Both of these are relatively cheap in terms of component cost (<~$100) but would be a reasonably long task to do (10 hours or more to make it passable). 

I think the best option would be to lean further into the OpenBuilds ecosystem and buy their Control Board ($300 CAD) which has very robust quick connectors. The machine already has a few of these connectors installed which came with the ACRO system and they're fantastic. Unfortunately there's not a easy way to interface connectors like these to the Arduino. The OpenBuilds controller uses the same GRBL firmware and USB interface that the Arduino is running so it really would just be plug and play into the current system. This also would make anybody who might want to build this in the future significantly happier that they don't have to toy around with custom PCB's. 

If we could make this quality of life upgrade that would be great! Let me know @lizzieinvancouver .

**Comment by lizzieinvancouver** [comment]
@afong3 It looks so professional and tidy now! Also, great purple color. 

> I think the best option would be to lean further into the OpenBuilds ecosystem and buy their Control Board ($300 CAD) which has very robust quick connectors. The machine already has a few of these connectors installed which came with the ACRO system and they're fantastic. Unfortunately there's not a easy way to interface connectors like these to the Arduino. The OpenBuilds controller uses the same GRBL firmware and USB interface that the Arduino is running so it really would just be plug and play into the current system. This also would make anybody who might want to build this in the future significantly happier that they don't have to toy around with custom PCB's.

Sounds reasonable. Let's do it!
