### ISSUE TITLE
Cheap camera with C-mount lens

### ISSUE THREAD

**Issue by afong3** [temporalecologylab/TreeRings#2]
# Summary
Budget camera option by taking C mount lenses commonly used for CCTV or machine vision applications. 

# Benefits:
1. Seemingly requires less frame height to get appropriately framed images than a handheld camera
2. A lighter camera will have less frame shake
3. Experimenting with various C-mount lenses will not be catastrophic to the budget
4. Camera mount does not need to fit a wide variety of handheld cameras
5. More budget friendly

# Drawbacks:
1. Potentially worse overall image quality
2. Likely will require more images to stitch together than a better camera with a wider field of view and equal resolution
3. No autofocus if the core is not flat

# Rough Field of View Calculations
Although it is not a subsitute for testing the camera and lens to verify the details of the sample is sufficient, I've included some rough calculations of field of view for camera and lens combinations. I reckon that this can be used as an estimate for how detailed of an image we will be able to capture.

[Link](https://docs.google.com/spreadsheets/d/1WUe56O0zvDdpGGkCNIC-_UNtWrSh-dZdjU4GiJDR2cY/edit?usp=sharing)

# Examples of Images:

(NOTE: they are using a 300x macro lens which I have not been able to find in stock)
[Shortcut to video](https://www.youtube.com/watch?v=goS7F2v741M&ab_channel=tata.geek.&t=190) slideshow of cells, rulers, PCB's, etc.

**Comment by lizzieinvancouver** [comment]
@afong3 Thanks for your work on this! If there's anything we need to buy in the US, let me know. I can order and bring back a few things -- though nothing too giant as I am already transporting a lot of tree cores.

**Comment by DeirdreLoughnan** [comment]
@afong3 @soleil-nocturne123 

I took some [images of a sanded cookies](https://github.com/temporalecologylab/TreeRings/tree/main/testImages) using a pi camera and a 180x lens using a 12MP sensor, just to get a sense of how well this will work. Also please ignore the scratches, we will get better at sanding with practice!

I think the camera set up works, but we would want an even better lens, and we could get up to 300x. 

<img width="884" alt="Screen Shot 2023-12-07 at 11 24 24 PM" src="https://github.com/temporalecologylab/TreeRings/assets/16216421/b4058dab-093a-46e1-9bdd-cacaa6315ae6">

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan This is awesome! Have i mentioned how excited I am? I am.

**Comment by afong3** [comment]
@DeirdreLoughnan this is very cool! Are you able to save them as .raw images? Also do you know the measured height and width that are in frame?

**Comment by afong3** [comment]
I've done some testing with the two lenses we have for the Raspberry Pi HQ camera. Some input would be great to see if we need any higher level of magnification or not. The images are slightly out of focus because the camera mount I am using is a bit finicky. 

| Camera                 | Lens                                         | Image                          |
| ---------------------- | ------------------------------------------------------ | ------------------------------ |
| Raspberry Pi HQ Camera | [SEEED Studio 300x Lens](https://www.mouser.ca/ProductDetail/Seeed-Studio/114992279?qs=sPbYRqrBIVkEZBNsZalWRw%3D%3D) | ![IMG-20240308-WA0003](https://github.com/temporalecologylab/TreeRings/assets/62484502/caefb8fc-8fea-4a18-87b3-3c90949520da) |
| Raspberry Pi HQ Camera | [SEEED Studio 300x Lens](https://www.mouser.ca/ProductDetail/Seeed-Studio/114992279?qs=sPbYRqrBIVkEZBNsZalWRw%3D%3D) | ![IMG-20240308-WA0002](https://github.com/temporalecologylab/TreeRings/assets/62484502/d45d3c9c-8a07-4f45-b08d-fc8ddb94c316) |
| Raspberry Pi HQ Camera | [Amazon 'Gringoo' Branded 130x Lens](https://www.amazon.ca/dp/B0BQWRVMXQ?ref=ppx_yo2ov_dt_b_product_details&th=1)    | ![1](https://github.com/temporalecologylab/TreeRings/assets/62484502/c7d3a8af-7f4b-44a1-a625-9045053f4513) |
| Raspberry Pi HQ Camera | [Amazon 'Gringoo' Branded 130x Lens](https://www.amazon.ca/dp/B0BQWRVMXQ?ref=ppx_yo2ov_dt_b_product_details&th=1)    | ![2](https://github.com/temporalecologylab/TreeRings/assets/62484502/581cf03e-6915-48ad-97b7-35641769f93e) |
| Raspberry Pi HQ Camera | [Amazon 'Gringoo' Branded 130x Lens](https://www.amazon.ca/dp/B0BQWRVMXQ?ref=ppx_yo2ov_dt_b_product_details&th=1)    | ![3](https://github.com/temporalecologylab/TreeRings/assets/62484502/dbf4be84-660e-43d6-9aba-ad5c3b3dcd5f) |
| Raspberry Pi HQ Camera | [Amazon 'Gringoo' Branded 130x Lens](https://www.amazon.ca/dp/B0BQWRVMXQ?ref=ppx_yo2ov_dt_b_product_details&th=1)    | ![4](https://github.com/temporalecologylab/TreeRings/assets/62484502/53f3a12d-d53d-47b7-9d24-abc4f1e55ef2)|

**Comment by lizzieinvancouver** [comment]
@afong3 Super cool! They look pretty to me, but we should get perspectives from people who have looked at more rings ... @FrederikBaumgarten @DeirdreLoughnan and @wangxm-forest -- thoughts? I suspect they are high enough mag and just the sanding is perhaps the issue where seeing some things is tricky?

**Comment by wangxm-forest** [comment]
I might not be a best person to make a comment here. I scanned all my tree cores with a scanner at 1200 dpi resolution...These look great to me.

**Comment by afong3** [comment]
The 300x lens is equivalent to about 38,000 dpi and the other lens is about 25,000 dpi.
