### ISSUE TITLE
Should we use a servo or stepper motor?

### ISSUE THREAD

**Issue by soleil-nocturne123** [temporalecologylab/TreeRings#4]
**STEPPER** requires a simpler control loop, and we can just select the one CaptuRING used. However:

1. We want to have a wider range of applications (a few mm to 50cm), so a **SERVO** motor would make it easier to scale down.
2. I imagine **SERVO** would help the camera move faster along the x and y case -- which is crucial in our case since the sample width and length might not be uniform.

**Comment by DeirdreLoughnan** [comment]
We discussed this at our Wednesday meeting. The key points I took away from the discussion were:

- STEPPER can still move at small increments and easier to program
- SERVO is faster, and would define the bounds of a sample faster, but harder to program
- We are not really time limited and using a STEPPER motor would still make the process much faster than current methods

We decided to move forward using the STEPPER motor.

@soleil-nocturne123 @kim-dajeong @afong3 do you have any additional points to add?

**Comment by lizzieinvancouver** [comment]
@soleil-nocturne123 Hope you've been able to order the motor! If it doesn't work out, we can try the other. 

Also, I started a refs page with a cool [new ref to check out](url)

**Comment by soleil-nocturne123** [comment]
@lizzieinvancouver and @DeirdreLoughnan I have just added the motors to the Excel ordering sheet
